export const Apiendpoints = {
  LOGIN: 'auth/signIn',
  LOGOUT: 'auth/logout',
  VERIFY_MPIN: 'auth/secureLogin',
  GETUSER: 'user/get-user',
  GET_USERS: 'admin/getUsers',
  MENUS: 'resource/menu',
  UPDATE_USER: 'admin/user',
  GETCLIENT: 'user/get-client',
  SAVECLIENT: 'user/save-client',
  SAVECLIENT_COMPANY: 'user/save-company-details',
  LOGO_UPLOAD: 'upload-logo',
  LOGO_GET: 'user/get-image',
  GET_COMPLAINTS: 'complaint/getAllComplaints',
  CREATE_COMPLAINT: 'complaint/createComplaint',
  UPDATE_COMPLAINT: 'complaint/updateComplaint',
  CLIENT_BLOCK_UNBLOCK: 'user/block-unblock',
  GET_BILLERS: 'operator/getBillers',
  GET_NOTIFICATIONS: 'notification/getNotification',
  UPDATE_NOTIFICATIONS: 'notification/update',
  BILLER_DETAILS: 'operator/getBillerDetails',
  GET_PLANS: 'plan/getPlans',
  CREATE_PLAN: 'plan/createPlan',
  UPDATE_PLAN: 'plan/updatePlan',
  DELETE_PLAN:'plan/deletePlan',
  GET_BANKS:'wallet/bank',
  GET_ACCOUNTS: 'accounts/getAccount',
  RECHARGE: 'prepaid/recharge',
  GET_SERVICETYPE: 'operator/getServiceType',
  BBPS_CATEGORY: 'operator/getCategories',
  BBPS_BILLERS: 'operator/getBbpsBillers',
  BBPS_BILLER_DETAILS: 'operator/getBbpsBillersDetails',
  CREDIT_REQ: 'wallet/creditRequest',
  GET_ADMIN_BANKS: 'wallet/bank',
  GET_MODES: 'wallet/getModes',
  GET_WALLET: 'wallet/fetchWallet',
  GET_TRANSACTIONS: 'transaction/getTransaction',
  RESET_TPIN: 'auth/resetTpin',
  ADD_REMITTER: '',
  UPDATE_USER_STATUS: 'admin/userStatus',
  GET_NOTIFICATION: 'notification/getNotification',
  NEPAL_TRANSFER_GET_MOBILE: 'nepal-transfer/getCustomerByMobileOrId',
  GET_RECENT_ACTIVITY:"transaction/recentActivity",
  CREATE_NOTIFICATION: 'notification/createNotification',
  OFFLINE_BILL_PAYMENT: 'utility/billPayment',
  BBPS_BILL_PAYMENT: 'bbps/billPayment',
  // BBPS
  FETCH_BILL: 'bbps/fetchBill',
  // CMS
  CREATE_ORDER_CMS: "user/createOrderCms",
  // DMT
  GET_REMITTER_DMT1: 'dmt1/getRemitter',
  BANK_SEARCH_DMT1:'dmt1/getBanks',
  ADD_BENE_DMT1:'dmt1/addBeneficiary',
  DELETE_BENE_DMT1: 'dmt1/deleteBeneficiary',
  DMI1_VALIDATE_OTP: 'dmt1/validateOtp',
  DMT1_VERIFY_BENE:'dmt1/verifyAccount',
  BANK_SEARCH_DMT2:'dmt2/getBanks',
  ADD_BENE_DMT2:'dmt2/addBeneficiary',
  DELETE_BENE_DMT2: 'dmt2/deleteBeneficiary',
  DMT1_MONEY_TRANSFER: 'dmt1/transactionDmt1',
  DMT2_MONEY_TRANSFER: 'dmt2/transactionDmt2',
  DMT1_ADD_REMITTER:"dmt1/addRemitter",
  
  DMT2_ADD_REMITTER:"dmt2/addRemitter",
  DMT1_VALIDATE_OTP:"dmt1/validateOtp",
  DMI2_VALIDATE_OTP: 'dmt2/validateOtp',
  GET_REMITTER_DMT2: 'dmt2/getRemitter',
  GET_SCHEMA: 'schema',
  REMITTER_PARAMS:"resource/getRemiterParams",
  // vendorpay
GET_VENDORS: "payments/getVendors",
ADD_VENDORS:'payments/addVendor',
DELETE_VENDOR:'payments/deleteVendor',
VENDOR_PAYMENT:"payments/vendorPayment",

// resourse
GET_NAV: 'resource/menu',

};
